
### 資料庫設定 ###
NAME = 'mapdb'
USERNAME = 'root'
PASSWORD = '11236018'

### 系統常數設定 ###

SEARCH_CITY = '台北市'
SEARCH_TYPE = '餐廳'
SEARCH_KEYWORD = SEARCH_CITY + ' ' + SEARCH_TYPE

REF_LOCATION = False

REPAIR_DATA = False
ENABLE_SCROLL_DOWN = True
HAVE_TO_GET_ALL_RESULTS = False

SPREADING_BRANCHES = False

MAXIMUM_TIMEOUT = 15
MAXIMUM_WAITING = 3
MAXIMUM_SAMPLES = 50
MINIMUM_SAMPLES = 30

TARGET_CITY = ''
