
### 資料庫設定 ###
NAME = 'map'
USERNAME = 'root'
PASSWORD = '11236018'

### 系統常數設定 ###

SEARCH_CITY = '台北市'
SEARCH_TYPE = '平價餐廳'
SEARCH_KEYWORD = SEARCH_CITY + ' ' + SEARCH_TYPE

REF_LOCATION = False

REPAIR_DATA = False
ENABLE_SCROLL_DOWN = True
HAVE_TO_GET_ALL_RESULTS = False

STORES_URLS = [

]

SPREADING_BRANCHES = False

PASS_TAGS = ['暫時關閉', '永久歇業']
EXPERIENCE_TARGET = ['餐點', '服務', '氣氛']
RECOMMEND_DISHES = '建議的餐點'

MAXIMUM_TIMEOUT = 15
MAXIMUM_WAITING = 3
MAXIMUM_SAMPLES = 1000
MINIMUM_SAMPLES = 30

MAX_COMMENT_YEARS = 3

TARGET_CITY = ''
